[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false
mainnet = []

[programs.localnet]
locked_sol_pnft = "3kLyy6249ZFsZyG74b6eSwuvDUVndkFM54cvK8gnietr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../../keys/devnet.json"

[scripts]
test = " ../node_modules/.bin/jest --preset ts-jest"
build-local = """
solana config get | grep -q 'RPC URL: https://api.mainnet' \
&& MAINNET_SERVER_AUTHORITY='TODO' cargo build \
|| DEVNET_SERVER_AUTHORITY='EiLANmnffXVXczyimnGEKSZpzwQ4TyuQXVAviqBji8TF' cargo build --features devnet
"""

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "fixtures/mpl_core.so"

[[migrations]]
name = "initialize_master"
script = "migrations/01_initialize_master.ts"

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
