# Generated by Django 5.1.3 on 2024-11-24 05:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import storymint.models.base
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(max_length=255, verbose_name="choice")),
            ],
            options={
                "verbose_name": "choice",
                "verbose_name_plural": "choices",
                "db_table": "storymint_choice",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
            ],
            options={
                "verbose_name": "node",
                "verbose_name_plural": "nodes",
                "db_table": "storymint_node",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True,
                        help_text="Base58 encoded Solana public key",
                        max_length=44,
                        unique=True,
                        verbose_name="address",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "storymint_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="images", verbose_name="image"
                    ),
                ),
                (
                    "metadata",
                    models.FileField(
                        blank=True, upload_to="metadata", verbose_name="metadata"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        default=storymint.models.base.get_default_attributes,
                        verbose_name="attributes",
                    ),
                ),
                (
                    "max_value",
                    models.PositiveIntegerField(default=5, verbose_name="max value"),
                ),
                (
                    "asset",
                    models.CharField(
                        db_index=True,
                        help_text="Base58 encoded Solana public key",
                        max_length=44,
                        unique=True,
                        verbose_name="asset",
                    ),
                ),
                (
                    "has_pending_metadata_update",
                    models.BooleanField(
                        default=False, verbose_name="has pending metadata update?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="storymint.node"
                    ),
                ),
            ],
            options={
                "verbose_name": "character",
                "verbose_name_plural": "characters",
                "db_table": "storymint_character",
            },
        ),
        migrations.CreateModel(
            name="CharacterChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_choices",
                        to="storymint.character",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_choices",
                        to="storymint.choice",
                    ),
                ),
            ],
            options={
                "verbose_name": "character choice",
                "verbose_name_plural": "character choices",
                "db_table": "storymint_character_choice",
            },
        ),
        migrations.AddField(
            model_name="choice",
            name="next_node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_nodes",
                to="storymint.node",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="storymint.node",
            ),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prerequisites",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storylines",
                        to="storymint.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "story",
                "verbose_name_plural": "story",
                "db_table": "storymint_story",
            },
        ),
        migrations.CreateModel(
            name="StoryPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="storymint.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "story path",
                "verbose_name_plural": "story paths",
                "db_table": "storymint_story_path",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="story_path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="storymint.storypath",
            ),
        ),
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "world",
                "verbose_name_plural": "worlds",
                "db_table": "storymint_world",
            },
        ),
        migrations.AddField(
            model_name="story",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="storymint.world",
            ),
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="images", verbose_name="image"
                    ),
                ),
                (
                    "metadata",
                    models.FileField(
                        blank=True, upload_to="metadata", verbose_name="metadata"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        default=storymint.models.base.get_default_attributes,
                        verbose_name="attributes",
                    ),
                ),
                (
                    "max_value",
                    models.PositiveIntegerField(default=5, verbose_name="max value"),
                ),
                (
                    "collection",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Base58 encoded Solana public key",
                        max_length=44,
                        unique=True,
                        verbose_name="collection",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="external url"),
                ),
                (
                    "generator",
                    models.CharField(
                        choices=[("generators.StarChart", "Star chart")],
                        default="generators.StarChart",
                        max_length=255,
                        verbose_name="generator",
                    ),
                ),
                (
                    "world",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="storymint.world",
                    ),
                ),
            ],
            options={
                "verbose_name": "metadata",
                "verbose_name_plural": "metadata",
                "db_table": "storymint_metadata",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="storymint.world",
            ),
        ),
    ]
